title : Damian Helme
tagline: Thoughts on tech stuff ...
author :
  name : Damian Helme
  email : tech@damianhelme.com
  github : dph01
  twitter : damianhelme
  feedburner : feedname

navigation :
  - archive.html
  - tags.html
  - categories.html
  
